# config/local.yaml

env: "local" 
storage_connection: 
  host: "localhost"
  port: 5432
  user: "gurebusan"
  dbname: "url-shortener-database"
  sslmode: "disable"
http_server: 
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s