env: "prod"
storage_connection:
  host: "postgres"
  port: 5432
  user: "postgres"
  dbname: url_shortener
  sslmode: "disable"
http_server:
  address: "0.0.0.0:8082"
  timeout: 4s
  idle_timeout: 60s
  user: "admin"